@startuml
actor Admin
participant SurgeyApointmentSystem

Admin -> SurgeyApointmentSystem : List Patient Profile By Email
activate SurgeyApointmentSystem

SurgeyApointmentSystem -> Admin : Searched Patient Profile
deactivate SurgeyApointmentSystem


@enduml
