@startuml
actor Admin
participant SurgeryApointmentSystem
participant MasterData


Admin -> SurgeryApointmentSystem : Create New Staff Profile
activate SurgeryApointmentSystem

SurgeryApointmentSystem -> MasterData : Create New Staff Profile
activate MasterData

MasterData --> SurgeryApointmentSystem : Staff Profile Created
deactivate MasterData

SurgeryApointmentSystem --> Admin : New Staff Profile Created
deactivate SurgeryApointmentSystem

@enduml
