@startuml
actor Admin
participant SurgeyAppointmentSystem

activate Admin

Admin -> SurgeyAppointmentSystem : Deactivate A Staff Profile
activate SurgeyAppointmentSystem

SurgeyAppointmentSystem -> Admin : Staff Profile Deactivated
deactivate SurgeyAppointmentSystem

deactivate Admin

@enduml
