@startuml
actor Admin
participant SurgeyAppointmentSystem

activate Admin

Admin -> SurgeyAppointmentSystem : Edit A Staff Profile
activate SurgeyAppointmentSystem

SurgeyAppointmentSystem -> Admin : Staff Profile Edited
deactivate SurgeyAppointmentSystem

deactivate Admin

@enduml
