@startuml
actor Admin
participant Routing
participant Controller
participant ApplicationService
participant Repository
participant Persistence
database Database

Admin -> Routing : List Patient Profiles By Email
activate Routing

Routing -> Controller : Forward Request To List Patient \nProfile By Email
activate Controller

Controller -> ApplicationService : List Patient Profile By Email
activate ApplicationService

ApplicationService -> Repository : Requests Patient Profile By Email
activate Repository

Repository -> Persistence : Requests Patient Profile By Email
activate Persistence

Persistence -> Database : Select Patient Profile By Email
activate Database

Database --> Persistence : Patient Profile Found
deactivate Database

Persistence --> Repository : Patient Profile Found
deactivate Persistence

Repository --> ApplicationService : Patient Profile Found
deactivate Repository

ApplicationService --> Controller : Patient Profile Found
deactivate ApplicationService

Controller --> Routing : Patient Profile Found
deactivate Controller

Routing --> Admin : Searched Patient Profile
deactivate Routing
@enduml
