@startuml
actor Admin
participant SurgeryAppointmentSystem

activate Admin

Admin -> SurgeryAppointmentSystem : Deactivate A Staff Profile
activate SurgeryAppointmentSystem

SurgeryAppointmentSystem -> Admin : Staff Profile Deactivated Successfully
deactivate SurgeryAppointmentSystem

deactivate Admin

@enduml
