@startuml
actor Admin
participant SurgeryAppointmentSystem

Admin -> SurgeryAppointmentSystem : Deactivate A Staff Profile
activate SurgeryAppointmentSystem

SurgeryAppointmentSystem -> Admin : Staff Profile Deactivated Successfully
deactivate SurgeryAppointmentSystem

@enduml
