@startuml

title US 5.1.8-Sequence Diagram Level 2

actor Admin
participant SurgeryAppointmentSystem
participant Backend
database DataBase

activate Admin

Admin -> SurgeryAppointmentSystem: create new patient profile

activate SurgeryAppointmentSystem

SurgeryAppointmentSystem -> Backend: create new patient profile
activate Backend

Backend -> DataBase:create new patient profile
activate DataBase

DataBase -->Backend:new patient profile created
deactivate DataBase

Backend --> SurgeryAppointmentSystem: new patient profile created
deactivate Backend

SurgeryAppointmentSystem --> Admin: new patient profile created
deactivate SurgeryAppointmentSystem
@enduml