@startuml
actor Admin
participant SurgeyApointmentSystem

activate Admin
Admin -> SurgeyApointmentSystem: edit operation type
activate SurgeyApointmentSystem

SurgeyApointmentSystem --> Admin: operation type edited
deactivate SurgeyApointmentSystem

@enduml
