@startuml
actor Admin
participant SurgeryAppointmentSystem
participant Backend
database DataBase


Admin -> SurgeryAppointmentSystem : Edit A Staff Profile (email, \nphoneNumber, specialization)
activate SurgeryAppointmentSystem

SurgeryAppointmentSystem -> Backend : Edit Staff Profile (email, \nphoneNumber, specialization)
activate Backend



SurgeryAppointmentSystem --> Admin : Staff Profile Edited Successfully
deactivate SurgeryAppointmentSystem

@enduml
