@startuml
actor Admin
participant Routing
participant Controller
participant ApplicationService
participant Repository
participant Persistence
database Database

activate Admin

Admin -> Routing: Edit Staff Profile Request
activate Routing

Routing -> Controller: Forward Request To Edit Staff Profile
activate Controller

Controller -> ApplicationService: Edit Staff Profile
activate ApplicationService

ApplicationService -> Repository: Request Active Staff By ID
activate Repository

Repository -> Persistence: Request Active Staff By ID
activate Persistence

Persistence -> Database: Get Active Staff By ID
activate Database

Database --> Persistence: Staff Found
deactivate Database

Persistence --> Repository: Staff Found
deactivate Persistence

Repository --> ApplicationService: Staff Found
deactivate Repository

ApplicationService -> ApplicationService: Deactivate Staff Profile
activate ApplicationService

ApplicationService -> Repository: Request Save Deactivated Staff Profile
activate Repository

Repository -> Persistence: Request Save Deactivated Staff Profile
activate Persistence

Persistence -> Database: Save Deactivated Staff Profile
activate Database

Database --> Persistence: Staff Profile Saved
deactivate Database

Persistence --> Repository: Staff Profile Saved
deactivate Persistence

Repository --> ApplicationService: Staff Profile Saved
deactivate Repository
deactivate ApplicationService

ApplicationService -> Controller: Staff Profile Deactivated
deactivate ApplicationService

Controller -> Routing: Staff Profile Deactivated
deactivate Controller

Routing -> Admin: Staff Profile Deactivated
deactivate Routing

deactivate Admin


@enduml
