@startuml

title US 5.1.8-Sequence Diagram Level 3

actor Admin
participant Routing
participant Routing
participant Controller
participant ApplicationService
participant Repository
participant Persistence
database DataBase

activate Admin

Admin -> Routing: create new patient profile

activate Routing

Routing -> Controller: create new patient profile

activate Controller

Controller -> ApplicationService: create new patient profile
activate ApplicationService

ApplicationService -> Repository: create a new patient profile
activate Repository

Repository -> Persistence:create a new patient profile
activate Persistence

Persistence -> DataBase:create a new patient profile
activate DataBase

DataBase --> Persistence:new patient profile inserted
deactivate DataBase

Persistence --> Repository:new patient profile inserted
deactivate Persistence

Repository --> ApplicationService: new patient profile inserted
deactivate Repository

ApplicationService --> Controller: new patient profile created

deactivate ApplicationService

Controller --> Routing: new patient profile created

deactivate Controller

Routing --> Admin: new patient profile created

@enduml