@startuml
actor Admin
participant Routing
participant Controller
participant ApplicationService
participant Repository
participant Persistence
database Database

activate Admin

Admin -> Routing : Deactivate A Staff Profile
activate Routing

Routing -> Controller : Forward Request To Deactivate A Staff Profile
activate Controller

Controller -> ApplicationService : Deactivate A Staff Profile
activate ApplicationService

ApplicationService -> Repository : Requests Staff Profile By Id
activate Repository

Repository -> Persistence : Requests Staff Profile By Id
activate Persistence

Persistence -> Database : Select Active Staff Profile By Id
activate Database

Database --> Persistence : Staff Profile Found
deactivate Database

Persistence --> Repository : Staff Profile Found
deactivate Persistence

Repository --> ApplicationService : Staff Profile Found
deactivate Repository

ApplicationService -> ApplicationService : Deactivate Staff Profile
activate ApplicationService

ApplicationService -> Repository : Update Staff Profile
activate Repository

Repository -> Persistence : Update Staff Profile
activate Persistence

Persistence -> Database : Update Staff Profile
activate Database

Database --> Persistence : Staff Profile Updated
deactivate Database

Persistence --> Repository : Staff Profile Updated
deactivate Persistence

Repository --> ApplicationService : Staff Profile Updated
deactivate Repository
deactivate ApplicationService

ApplicationService --> Controller : Staff Profile Deactivated Successfully
deactivate ApplicationService

Controller --> Routing : Staff Profile Deactivated Successfully
deactivate Controller

Routing --> Admin : Staff Profile Deactivated Successfully
deactivate Routing

deactivate Admin

@enduml
