@startuml
title US 5.1.9-Sequence Diagram Level 1

actor Admin
participant SurgeryAppointmentSystem

activate Admin
Admin-> SurgeryAppointmentSystem: edit patient's profile
activate SurgeryAppointmentSystem

SurgeryAppointmentSystem --> Admin: patient's profile edited
deactivate SurgeryAppointmentSystem

deactivate Admin
@enduml