@startuml
actor Admin
participant SurgeyApointmentSystem

Admin -> SurgeyApointmentSystem : Create New Staff Profile
activate SurgeyApointmentSystem

SurgeyApointmentSystem -> Admin : New Staff Profile Created
deactivate SurgeyApointmentSystem

@enduml
