@startuml
actor Admin
participant SurgeyApointmentSystem

Admin -> SurgeyApointmentSystem : Search Staff Profiles By Specialization
activate SurgeyApointmentSystem

SurgeyApointmentSystem -> Admin : Searched Staff Profile
deactivate SurgeyApointmentSystem

@enduml
