@startuml
actor Staff
participant Routing
participant Controller
participant ApplicationService
participant Repository
participant Persistence
database Database
boundary IAM_API as "External IAM API"

activate Staff
Staff -> Routing: logs in into the system

activate Routing
Routing -> Controller: forward request to login
activate Controller

Controller -> ApplicationService: logs in into the system
activate ApplicationService

ApplicationService -> IAM_API: send data to login into the system
activate IAM_API

IAM_API --> ApplicationService: sends user session
deactivate IAM_API

ApplicationService -> Repository: requests user data
activate Repository

Repository -> Persistence: requests user data
activate Persistence

Persistence -> Database: asks for user data
activate Database
Database --> Persistence: send user data
deactivate Database

Persistence --> Repository: user data retrieved
deactivate Persistence

Repository --> ApplicationService: user data retrieved
deactivate Repository

ApplicationService -> ApplicationService: updates user session with\nuser data from database

ApplicationService --> Controller: user logged in
deactivate ApplicationService

Controller --> Routing: user logged in
deactivate Controller

Routing --> Staff: user logged in
deactivate Routing

@enduml
