@startuml
actor Staff
participant SurgicalAppointmentSystem
participant Routing
participant Controller
participant ApplicationService
participant Backend
participant Repository
participant Persistence
boundary IAM_API as "External IAM API"
database Database

activate Staff
Staff -> SurgicalAppointmentSystem: logs in into the system
activate SurgicalAppointmentSystem

SurgicalAppointmentSystem -> Routing: forward request to login
activate Routing
Routing -> Controller: forward request to login
activate Controller

Controller -> ApplicationService: logs in into the system
activate ApplicationService

ApplicationService -> Backend: forward login request
activate Backend

Backend -> IAM_API: send data to login into the system
activate IAM_API

IAM_API --> Backend: sends user session
deactivate IAM_API

Backend -> Repository: requests user data
activate Repository

Repository -> Persistence: requests user data
activate Persistence

Persistence -> Database: asks for user data
activate Database
Database --> Persistence: send user data
deactivate Database

Persistence --> Repository: user data retrieved
deactivate Persistence

Repository --> Backend: user data retrieved
deactivate Repository

Backend -> Backend: updates user session with\nuser data from database

Backend --> ApplicationService: user logged in
deactivate Backend

ApplicationService --> Controller: user logged in
deactivate ApplicationService

Controller --> Routing: user logged in
deactivate Controller

Routing --> SurgicalAppointmentSystem: user logged in
deactivate Routing

SurgicalAppointmentSystem --> Staff: gives access to the staff
deactivate SurgicalAppointmentSystem
@enduml
