@startuml
title Update Profile

actor Patient
participant "Surgical apointment system" as App
activate App
activate Patient
Patient -> App: Request profile update
App -> Patient: Data request
Patient -> App: Provide data
alt data is email or phone
App -> Patient: Send email confirmation
Patient -> App: Confirm email
end alt 
App -> App: Validate data
App -> App: Update profile
App -> Patient: display success message
App->Patient: success message

deactivate App
deactivate Patient
@enduml
