@startuml
title Registro de Paciente


actor Patient
participant "Surgical apointment system" as App
participant "IAM " as IAM

activate App
activate Patient

Patient -> App: Request registration
App ->Patient: Request email and phone
Patient -> App: Provide email and phone
App -> IAM: Validate email and phone
IAM --> App: Email and phone are valid
App -> App: Create patient profile
App -> Patient: Send a email with a link to complete registration
Patient -> App: Click on the link
App -> App: Validate the link
App -> Patient: success message

deactivate App
deactivate Patient
@enduml
