@startuml
actor Admin
participant SurgeryApointmentSystem
participant MasterData
participant BackEnd
participant Database

Admin -> SurgeryApointmentSystem : Create New Staff Profile
activate SurgeryApointmentSystem

SurgeryApointmentSystem -> MasterData : Create New Staff Profile
activate MasterData

MasterData -> BackEnd : Create New Staff Profile
activate BackEnd

BackEnd -> BackEnd : Creates New Staff Profile
activate BackEnd

BackEnd -> Database : Insert New Staff Profile
activate Database

Database --> BackEnd : New Staff Profile Inserted
deactivate Database

deactivate BackEnd

BackEnd --> MasterData : New Staff Profile Created

deactivate BackEnd

MasterData --> SurgeryApointmentSystem : Staff Profile Created
deactivate MasterData

SurgeryApointmentSystem --> Admin : New Staff Profile Created
deactivate SurgeryApointmentSystem

@enduml
