@startuml

title US 5.1.10 Sequence Diagram Level 3

actor Admin
participant Routing
participant Controller
participant ApplicationService
participant Repository
participant Persistence
database DataBase

activate Admin

Admin -> Routing: delete patient profile

activate Routing

Routing -> Controller: delete patient profile

activate Controller

Controller -> ApplicationService: delete patient profile
activate ApplicationService

ApplicationService -> Repository: delete patient profile
activate Repository

Repository -> Persistence:anonymize patient profile
activate Persistence

Persistence ->DataBase:anonymize patient profile
activate DataBase

DataBase -->Persistence: anonymized patient profile
deactivate DataBase

Persistence --> Repository:anonymized patient profile
deactivate Persistence


Repository --> ApplicationService: patient profile deleted
deactivate Repository

ApplicationService --> Controller: patient profile deleted

deactivate ApplicationService

Controller --> Routing: patient profile deleted

deactivate Controller

Routing --> Admin: patient profile deleted

@enduml