@startuml

title US 5.1.3-Register Patient User-\nSequence Diagram Level 1

actor Patient
participant SurgeryAppointmentSystem

activate Patient
Patient-> SurgeryAppointmentSystem: create new Patient user
activate SurgeryAppointmentSystem

SurgeryAppointmentSystem --> Patient: new Patient user created
deactivate SurgeryAppointmentSystem

@enduml