@startuml
actor Admin
participant SurgeryAppointmentSystem
participant Backend
database Database

activate Admin

Admin -> SurgeryAppointmentSystem : Edit A Staff Profile
activate SurgeryAppointmentSystem

SurgeryAppointmentSystem -> Backend : Edit Staff Profile
activate Backend

Backend -> Database : Get Active Staff Profile
activate Database

Database --> Backend : Active Staff Profile Retrieved
deactivate Database

Backend -> Backend : Edit Staff Profile
activate Backend

Backend --> Database : Save Edited Staff
activate Database

Database --> Backend : Staff Profile Saved
deactivate Database
deactivate Backend

Backend --> SurgeryAppointmentSystem : Staff Profile Edited
deactivate Backend

SurgeryAppointmentSystem --> Admin : Staff Profile Edited
deactivate SurgeryAppointmentSystem

deactivate Admin

@enduml
