@startuml
actor Admin
participant SurgeryAppointmentSystem
participant Backend
database Database

activate Admin

Admin -> SurgeryAppointmentSystem : Deactivate A Staff Profile
activate SurgeryAppointmentSystem

SurgeryAppointmentSystem -> Backend : Deactivate Staff Profile
activate Backend

Backend -> Database : Get Active Staff Profile
activate Database

Database --> Backend : Active Staff Profile Retrieved
deactivate Database

Backend -> Backend : Deactivate Staff Profile
activate Backend

Backend --> Database : Save Deactivated Staff
activate Database

Database --> Backend : Staff Profile Saved
deactivate Database
deactivate Backend

Backend --> SurgeryAppointmentSystem : Staff Profile Deactivated
deactivate Backend

SurgeryAppointmentSystem --> Admin : Staff Profile Deactivated
deactivate SurgeryAppointmentSystem

deactivate Admin

@enduml
