@startuml
title US 5.1.10 Sequence Diagram Level 2

actor Admin
participant SurgeryAppointmentSystem
participant Backend
database DataBase

activate Admin

Admin -> SurgeryAppointmentSystem: delete patient profile

activate SurgeryAppointmentSystem

SurgeryAppointmentSystem -> Backend: delete patient profile
activate Backend

Backend -> DataBase: anonymize patient profile
activate DataBase

DataBase --> Backend: patient profile anonymized
deactivate DataBase

Backend --> SurgeryAppointmentSystem: patient profile deleted
deactivate Backend

SurgeryAppointmentSystem --> Admin: patient profile deleted
deactivate SurgeryAppointmentSystem
@enduml